import 'server-only';

// =============================================================================
// BRANCH CONFLICT PATTERNS (Declarative Format)
// =============================================================================
// All negative Earthly Branch interactions expressed as PatternSpecs.
// Ported from api/library/pattern_engine/patterns/branch_conflicts.py
// =============================================================================

import {
  type PatternSpec,
  PatternCategory,
  NodeType,
  LifeDomain,
  BadgeType,
} from '../pattern-spec';

// ---------------------------------------------------------------------------
// CLASHES (地支沖)
// ---------------------------------------------------------------------------

export const CLASHES_PATTERNS: PatternSpec[] = [
  { id: "CLASH~Zi-Wu~opposite", category: PatternCategory.CLASH, priority: 200, chinese_name: "子午沖", english_name: "Rat-Horse Clash", node_filters: [{ branches: new Set(["Zi", "Wu"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 15.0, distance_multipliers: [1.0, 0.85, 0.7], qi_effects: [{ target: "source", qi_change: -10.0, is_percentage: false }, { target: "target", qi_change: -6.18, is_percentage: false }], badge_type: BadgeType.CLASH, life_domains: new Set([LifeDomain.HEALTH, LifeDomain.RELATIONSHIP, LifeDomain.CAREER]), pillar_meanings: { year: "Early life instability, family conflicts", month: "Career disruptions, authority clashes", day: "Relationship turmoil, inner conflict", hour: "Late life changes, children's challenges" }, description: "Water-Fire opposition - emotional vs passionate conflict", classical_source: "三命通會" },
  { id: "CLASH~Chou-Wei~same", category: PatternCategory.CLASH, priority: 200, chinese_name: "丑未沖", english_name: "Ox-Goat Clash", node_filters: [{ branches: new Set(["Chou", "Wei"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 12.0, distance_multipliers: [1.0, 0.85, 0.7], qi_effects: [{ target: "all", qi_change: -8.0, is_percentage: false }], badge_type: BadgeType.CLASH, life_domains: new Set([LifeDomain.FAMILY, LifeDomain.WEALTH, LifeDomain.HEALTH]), description: "Earth-Earth same element clash - stubborn conflict" },
  { id: "CLASH~Yin-Shen~opposite", category: PatternCategory.CLASH, priority: 200, chinese_name: "寅申沖", english_name: "Tiger-Monkey Clash", node_filters: [{ branches: new Set(["Yin", "Shen"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 15.0, distance_multipliers: [1.0, 0.85, 0.7], qi_effects: [{ target: "source", qi_change: -10.0, is_percentage: false }, { target: "target", qi_change: -6.18, is_percentage: false }], badge_type: BadgeType.CLASH, life_domains: new Set([LifeDomain.HEALTH, LifeDomain.TRAVEL, LifeDomain.CAREER]), description: "Wood-Metal opposition - growth vs cutting conflict" },
  { id: "CLASH~Mao-You~opposite", category: PatternCategory.CLASH, priority: 200, chinese_name: "卯酉沖", english_name: "Rabbit-Rooster Clash", node_filters: [{ branches: new Set(["Mao", "You"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 15.0, distance_multipliers: [1.0, 0.85, 0.7], qi_effects: [{ target: "source", qi_change: -10.0, is_percentage: false }, { target: "target", qi_change: -6.18, is_percentage: false }], badge_type: BadgeType.CLASH, life_domains: new Set([LifeDomain.HEALTH, LifeDomain.RELATIONSHIP, LifeDomain.LEGAL]), description: "Pure Wood-Metal opposition - precision cuts growth" },
  { id: "CLASH~Chen-Xu~same", category: PatternCategory.CLASH, priority: 200, chinese_name: "辰戌沖", english_name: "Dragon-Dog Clash", node_filters: [{ branches: new Set(["Chen", "Xu"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 12.0, distance_multipliers: [1.0, 0.85, 0.7], qi_effects: [{ target: "all", qi_change: -8.0, is_percentage: false }], badge_type: BadgeType.CLASH, life_domains: new Set([LifeDomain.WEALTH, LifeDomain.CAREER, LifeDomain.FAMILY]), description: "Earth-Earth storage clash - both are element storages" },
  { id: "CLASH~Si-Hai~opposite", category: PatternCategory.CLASH, priority: 200, chinese_name: "巳亥沖", english_name: "Snake-Pig Clash", node_filters: [{ branches: new Set(["Si", "Hai"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 15.0, distance_multipliers: [1.0, 0.85, 0.7], qi_effects: [{ target: "source", qi_change: -10.0, is_percentage: false }, { target: "target", qi_change: -6.18, is_percentage: false }], badge_type: BadgeType.CLASH, life_domains: new Set([LifeDomain.TRAVEL, LifeDomain.CAREER, LifeDomain.HEALTH]), description: "Fire-Water Yi Ma clash - travel and movement disruption" },
];

// ---------------------------------------------------------------------------
// PUNISHMENTS (刑)
// ---------------------------------------------------------------------------

export const PUNISHMENTS_PATTERNS: PatternSpec[] = [
  { id: "PUNISHMENT~Yin-Si-Shen~shi_xing", category: PatternCategory.PUNISHMENT, priority: 210, chinese_name: "勢刑", english_name: "Bullying Punishment (Tiger-Snake-Monkey)", node_filters: [{ branches: new Set(["Yin", "Si", "Shen"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 3, base_score_combined: 18.0, distance_multipliers: [1.0, 0.9, 0.8], qi_effects: [{ target: "all", qi_change: -12.0, is_percentage: false }], badge_type: BadgeType.PUNISHMENT, life_domains: new Set([LifeDomain.HEALTH, LifeDomain.LEGAL, LifeDomain.CAREER]), description: "Three powerful branches (Wood-Fire-Metal) in mutual conflict - severe trauma", classical_source: "三命通會: 恃勢之刑" },
  { id: "PUNISHMENT~Chou-Wei-Xu~wu_li_xing", category: PatternCategory.PUNISHMENT, priority: 215, chinese_name: "無禮刑", english_name: "Rudeness Punishment (Ox-Goat-Dog)", node_filters: [{ branches: new Set(["Chou", "Wei", "Xu"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 3, base_score_combined: 15.0, distance_multipliers: [1.0, 0.85, 0.7], qi_effects: [{ target: "all", qi_change: -10.0, is_percentage: false }], badge_type: BadgeType.PUNISHMENT, life_domains: new Set([LifeDomain.RELATIONSHIP, LifeDomain.FAMILY, LifeDomain.HEALTH]), description: "Three Earth branches in mutual disrespect - relationship damage", classical_source: "三命通會: 無禮之刑" },
  { id: "PUNISHMENT~Zi-Mao~en_xing", category: PatternCategory.PUNISHMENT, priority: 220, chinese_name: "恩刑", english_name: "Ungrateful Punishment (Rat-Rabbit)", node_filters: [{ branches: new Set(["Zi", "Mao"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 10.0, distance_multipliers: [1.0, 0.8, 0.6], qi_effects: [{ target: "source", qi_change: -7.0, is_percentage: false }, { target: "target", qi_change: -4.3, is_percentage: false }], badge_type: BadgeType.PUNISHMENT, life_domains: new Set([LifeDomain.RELATIONSHIP, LifeDomain.FAMILY, LifeDomain.CAREER]), description: "Water nurtures Wood, but Wood punishes Water - betrayal by those you helped", classical_source: "三命通會: 持恩之刑" },
  { id: "PUNISHMENT~Chen-Chen~zi_xing", category: PatternCategory.PUNISHMENT, priority: 230, chinese_name: "辰自刑", english_name: "Dragon Self-Punishment", node_filters: [{ branches: new Set(["Chen"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 8.0, distance_multipliers: [1.0, 0.75, 0.5], qi_effects: [{ target: "all", qi_change: -6.0, is_percentage: false }], badge_type: BadgeType.PUNISHMENT, life_domains: new Set([LifeDomain.HEALTH, LifeDomain.CAREER]), description: "Earth Dragon - stubborn pride leads to isolation" },
  { id: "PUNISHMENT~Wu-Wu~zi_xing", category: PatternCategory.PUNISHMENT, priority: 230, chinese_name: "午自刑", english_name: "Horse Self-Punishment", node_filters: [{ branches: new Set(["Wu"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 8.0, distance_multipliers: [1.0, 0.75, 0.5], qi_effects: [{ target: "all", qi_change: -6.0, is_percentage: false }], badge_type: BadgeType.PUNISHMENT, life_domains: new Set([LifeDomain.HEALTH, LifeDomain.RELATIONSHIP]), description: "Fire Horse - restless energy burns itself out" },
  { id: "PUNISHMENT~You-You~zi_xing", category: PatternCategory.PUNISHMENT, priority: 230, chinese_name: "酉自刑", english_name: "Rooster Self-Punishment", node_filters: [{ branches: new Set(["You"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 8.0, distance_multipliers: [1.0, 0.75, 0.5], qi_effects: [{ target: "all", qi_change: -6.0, is_percentage: false }], badge_type: BadgeType.PUNISHMENT, life_domains: new Set([LifeDomain.HEALTH, LifeDomain.RELATIONSHIP]), description: "Metal Rooster - perfectionism leads to self-criticism" },
  { id: "PUNISHMENT~Hai-Hai~zi_xing", category: PatternCategory.PUNISHMENT, priority: 230, chinese_name: "亥自刑", english_name: "Pig Self-Punishment", node_filters: [{ branches: new Set(["Hai"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 8.0, distance_multipliers: [1.0, 0.75, 0.5], qi_effects: [{ target: "all", qi_change: -6.0, is_percentage: false }], badge_type: BadgeType.PUNISHMENT, life_domains: new Set([LifeDomain.HEALTH, LifeDomain.WEALTH]), description: "Water Pig - indulgence leads to self-harm" },
];

// ---------------------------------------------------------------------------
// HARMS (害)
// ---------------------------------------------------------------------------

export const HARMS_PATTERNS: PatternSpec[] = [
  { id: "HARM~Zi-Wei~", category: PatternCategory.HARM, priority: 240, chinese_name: "子未害", english_name: "Rat-Goat Harm", node_filters: [{ branches: new Set(["Zi", "Wei"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 10.0, distance_multipliers: [1.0, 0.8, 0.6], qi_effects: [{ target: "source", qi_change: -7.0, is_percentage: false }, { target: "target", qi_change: -4.3, is_percentage: false }], badge_type: BadgeType.HARM, life_domains: new Set([LifeDomain.RELATIONSHIP, LifeDomain.HEALTH]), description: "Water meets Earth - subtle undermining through absorption" },
  { id: "HARM~Chou-Wu~", category: PatternCategory.HARM, priority: 240, chinese_name: "丑午害", english_name: "Ox-Horse Harm", node_filters: [{ branches: new Set(["Chou", "Wu"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 10.0, distance_multipliers: [1.0, 0.8, 0.6], qi_effects: [{ target: "source", qi_change: -7.0, is_percentage: false }, { target: "target", qi_change: -4.3, is_percentage: false }], badge_type: BadgeType.HARM, life_domains: new Set([LifeDomain.RELATIONSHIP, LifeDomain.HEALTH]), description: "Fire meets Earth storage - passion smothered" },
  { id: "HARM~Yin-Si~", category: PatternCategory.HARM, priority: 240, chinese_name: "寅巳害", english_name: "Tiger-Snake Harm", node_filters: [{ branches: new Set(["Yin", "Si"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 10.0, distance_multipliers: [1.0, 0.8, 0.6], qi_effects: [{ target: "source", qi_change: -7.0, is_percentage: false }, { target: "target", qi_change: -4.3, is_percentage: false }], badge_type: BadgeType.HARM, life_domains: new Set([LifeDomain.HEALTH, LifeDomain.CAREER]), description: "Wood feeds Fire excessively - depletion through giving" },
  { id: "HARM~Mao-Chen~", category: PatternCategory.HARM, priority: 240, chinese_name: "卯辰害", english_name: "Rabbit-Dragon Harm", node_filters: [{ branches: new Set(["Mao", "Chen"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 10.0, distance_multipliers: [1.0, 0.8, 0.6], qi_effects: [{ target: "source", qi_change: -7.0, is_percentage: false }, { target: "target", qi_change: -4.3, is_percentage: false }], badge_type: BadgeType.HARM, life_domains: new Set([LifeDomain.CAREER, LifeDomain.RELATIONSHIP]), description: "Wood controls Earth - overextension causing harm" },
  { id: "HARM~Shen-Hai~", category: PatternCategory.HARM, priority: 240, chinese_name: "申亥害", english_name: "Monkey-Pig Harm", node_filters: [{ branches: new Set(["Shen", "Hai"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 10.0, distance_multipliers: [1.0, 0.8, 0.6], qi_effects: [{ target: "source", qi_change: -7.0, is_percentage: false }, { target: "target", qi_change: -4.3, is_percentage: false }], badge_type: BadgeType.HARM, life_domains: new Set([LifeDomain.TRAVEL, LifeDomain.CAREER]), description: "Metal produces Water - excessive giving depletes" },
  { id: "HARM~You-Xu~", category: PatternCategory.HARM, priority: 240, chinese_name: "酉戌害", english_name: "Rooster-Dog Harm", node_filters: [{ branches: new Set(["You", "Xu"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 10.0, distance_multipliers: [1.0, 0.8, 0.6], qi_effects: [{ target: "source", qi_change: -7.0, is_percentage: false }, { target: "target", qi_change: -4.3, is_percentage: false }], badge_type: BadgeType.HARM, life_domains: new Set([LifeDomain.RELATIONSHIP, LifeDomain.FAMILY]), description: "Metal meets Earth Fire storage - hidden fire harms metal" },
];

// ---------------------------------------------------------------------------
// DESTRUCTION (破)
// ---------------------------------------------------------------------------

export const DESTRUCTION_PATTERNS: PatternSpec[] = [
  { id: "DESTRUCTION~Zi-You~", category: PatternCategory.DESTRUCTION, priority: 250, chinese_name: "子酉破", english_name: "Rat-Rooster Destruction", node_filters: [{ branches: new Set(["Zi", "You"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 7.0, distance_multipliers: [1.0, 0.75, 0.5], qi_effects: [{ target: "source", qi_change: -5.0, is_percentage: false }, { target: "target", qi_change: -3.0, is_percentage: false }], badge_type: BadgeType.DESTRUCTION, life_domains: new Set([LifeDomain.RELATIONSHIP, LifeDomain.CAREER]), description: "Metal produces Water but creates friction in process" },
  { id: "DESTRUCTION~Chou-Chen~", category: PatternCategory.DESTRUCTION, priority: 250, chinese_name: "丑辰破", english_name: "Ox-Dragon Destruction", node_filters: [{ branches: new Set(["Chou", "Chen"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 6.0, distance_multipliers: [1.0, 0.75, 0.5], qi_effects: [{ target: "all", qi_change: -4.0, is_percentage: false }], badge_type: BadgeType.DESTRUCTION, life_domains: new Set([LifeDomain.WEALTH, LifeDomain.CAREER]), description: "Two Earth storages in friction - storage conflicts" },
  { id: "DESTRUCTION~Mao-Wu~", category: PatternCategory.DESTRUCTION, priority: 250, chinese_name: "卯午破", english_name: "Rabbit-Horse Destruction", node_filters: [{ branches: new Set(["Mao", "Wu"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 7.0, distance_multipliers: [1.0, 0.75, 0.5], qi_effects: [{ target: "source", qi_change: -5.0, is_percentage: false }, { target: "target", qi_change: -3.0, is_percentage: false }], badge_type: BadgeType.DESTRUCTION, life_domains: new Set([LifeDomain.HEALTH, LifeDomain.RELATIONSHIP]), description: "Wood feeds Fire excessively in destruction" },
  { id: "DESTRUCTION~Wei-Xu~", category: PatternCategory.DESTRUCTION, priority: 250, chinese_name: "未戌破", english_name: "Goat-Dog Destruction", node_filters: [{ branches: new Set(["Wei", "Xu"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 6.0, distance_multipliers: [1.0, 0.75, 0.5], qi_effects: [{ target: "all", qi_change: -4.0, is_percentage: false }], badge_type: BadgeType.DESTRUCTION, life_domains: new Set([LifeDomain.FAMILY, LifeDomain.WEALTH]), description: "Earth storage friction - Wood and Fire storages clash" },
  { id: "DESTRUCTION~Si-Shen~", category: PatternCategory.DESTRUCTION, priority: 250, chinese_name: "巳申破", english_name: "Snake-Monkey Destruction", node_filters: [{ branches: new Set(["Si", "Shen"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 7.0, distance_multipliers: [1.0, 0.75, 0.5], qi_effects: [{ target: "source", qi_change: -5.0, is_percentage: false }, { target: "target", qi_change: -3.0, is_percentage: false }], badge_type: BadgeType.DESTRUCTION, life_domains: new Set([LifeDomain.CAREER, LifeDomain.HEALTH]), description: "Fire controls Metal with friction" },
  { id: "DESTRUCTION~Hai-Yin~", category: PatternCategory.DESTRUCTION, priority: 250, chinese_name: "亥寅破", english_name: "Pig-Tiger Destruction", node_filters: [{ branches: new Set(["Hai", "Yin"]), node_types: new Set([NodeType.EARTHLY_BRANCH]) }], min_nodes: 2, max_nodes: 2, base_score_combined: 7.0, distance_multipliers: [1.0, 0.75, 0.5], qi_effects: [{ target: "source", qi_change: -5.0, is_percentage: false }, { target: "target", qi_change: -3.0, is_percentage: false }], badge_type: BadgeType.DESTRUCTION, life_domains: new Set([LifeDomain.EDUCATION, LifeDomain.HEALTH]), description: "Water produces Wood with friction" },
];

// ---------------------------------------------------------------------------
// COMBINED EXPORT
// ---------------------------------------------------------------------------

export const ALL_BRANCH_CONFLICT_PATTERNS: PatternSpec[] = [
  ...CLASHES_PATTERNS,
  ...PUNISHMENTS_PATTERNS,
  ...HARMS_PATTERNS,
  ...DESTRUCTION_PATTERNS,
];

export function getAllBranchConflictPatterns(): PatternSpec[] {
  return [...ALL_BRANCH_CONFLICT_PATTERNS];
}
